package xzkbauth.util;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * cmb后台账号 This class was generated by MyBatis Generator. This class corresponds to the database
 * table sy_user
 *
 * @mbggenerated do_not_delete_during_merge
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SyUser implements Serializable {
  private static final long serialVersionUID = 8318184504667506911L;
  /** 有效 */
  public static final String SYUSER_STATUS_VALID = "1";
  /** 无效 */
  public static final String SYUSER_STATUS_INVALID = "0";
  /** 归属 1-c端用户 2-b端用户 3-cmb端用户 */
  public static final Integer SYUSER_ATTRIBUTION_C = 1;

  public static final Integer SYUSER_ATTRIBUTION_B = 2;
  public static final Integer SYUSER_ATTRIBUTION_CMB = 3;
  /** 接收短信通知 0-否 1-是 */
  public static final Integer RECEIVEMSG_YES = 1;

  public static final Integer RECEIVEMSG_NO = 0;

  // ID
  private Integer id;
  // 分行码
  private String branchCod;
  // 登录名
  private String userCod;
  // 密码
  private String password;
  // 验证码(手机)
  private String verifyCode;
  // 用户名
  private String userName;
  // 用户类型
  private String type;
  // 手机
  private String phone;
  // 用户状态
  private String status;
  // 头像
  private Integer imgHead;
  // 插入日期
  private Date insertDate;
  // 更新日期
  private Date updateDate;
  /** 备注 */
  private String remark;
  /** 归属；1-c端，2-b端，3-cmb端 */
  private Integer attribution;
  /** 商户id */
  private Integer merchantId;
  /** 门店id */
  private Integer storeId;
  /** 最后更新人id */
  private Integer lastUpdateUser;
  /** 初始登录密码，针对b端商家 */
  private String originPassword;

  private String branchName;
  /** 校验码(随机生成) */
  private String code;

  private String role;

  private String roleName;
  /** 最近登录时间 */
  private Date currentLoginTime;
  /** 接收短信通知 0-否 1-是 */
  private Integer receiveMsg;
  /** 是否允许撤销非本人的收款记录 1-只允许撤销本人的收款记录 2-允许撤销无法确定收银员的收款记录（如用户扫二维码消费） */
  private Integer cancelAuth;
  /** 是否能通过微信分享收款 0-不允许(默认) 1-允许 */
  private Integer canShareWeiXin;
  /** 商户码 */
  private String merchantCod;
  /** 私钥 */
  private String privateKey;
  /** 公钥 */
  private String publicKey;
  /** 短信验证码 */
  private String phoneCode;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.ID
   *
   * @return the value of sy_user.ID
   * @mbggenerated
   */
  public String getPhoneCode() {
    return phoneCode;
  }

  public void setPhoneCode(String phoneCode) {
    this.phoneCode = phoneCode;
  }

  public Integer getId() {
    return id;
  }

  public String getRoleName() {
    return roleName;
  }

  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.ID
   *
   * @param id the value for sy_user.ID
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.branch_cod
   *
   * @return the value of sy_user.branch_cod
   * @mbggenerated
   */
  public String getBranchCod() {
    return branchCod;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.branch_cod
   *
   * @param branchCod the value for sy_user.branch_cod
   * @mbggenerated
   */
  public void setBranchCod(String branchCod) {
    this.branchCod = branchCod == null ? null : branchCod.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.USER_COD
   *
   * @return the value of sy_user.USER_COD
   * @mbggenerated
   */
  public String getUserCod() {
    return userCod;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.USER_COD
   *
   * @param userCod the value for sy_user.USER_COD
   * @mbggenerated
   */
  public void setUserCod(String userCod) {
    this.userCod = userCod == null ? null : userCod.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.USER_NAME
   *
   * @return the value of sy_user.USER_NAME
   * @mbggenerated
   */
  public String getUserName() {
    return userName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.USER_NAME
   *
   * @param userName the value for sy_user.USER_NAME
   * @mbggenerated
   */
  public void setUserName(String userName) {
    this.userName = userName == null ? null : userName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.PASS_WORD
   *
   * @return the value of sy_user.PASS_WORD
   * @mbggenerated
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.PASS_WORD
   *
   * @param password the value for sy_user.PASS_WORD
   * @mbggenerated
   */
  public void setPassword(String password) {
    this.password = password == null ? null : password.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.PHONE
   *
   * @return the value of sy_user.PHONE
   * @mbggenerated
   */
  public String getPhone() {
    return phone;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.PHONE
   *
   * @param phone the value for sy_user.PHONE
   * @mbggenerated
   */
  public void setPhone(String phone) {
    this.phone = phone == null ? null : phone.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.STATUS
   *
   * @return the value of sy_user.STATUS
   * @mbggenerated
   */
  public String getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.STATUS
   *
   * @param status the value for sy_user.STATUS
   * @mbggenerated
   */
  public void setStatus(String status) {
    this.status = status == null ? null : status.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.IMG_HEAD
   *
   * @return the value of sy_user.IMG_HEAD
   * @mbggenerated
   */
  public Integer getImgHead() {
    return imgHead;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.IMG_HEAD
   *
   * @param imgHead the value for sy_user.IMG_HEAD
   * @mbggenerated
   */
  public void setImgHead(Integer imgHead) {
    this.imgHead = imgHead;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.INSERT_DATE
   *
   * @return the value of sy_user.INSERT_DATE
   * @mbggenerated
   */
  public Date getInsertDate() {
    return insertDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.INSERT_DATE
   *
   * @param insertDate the value for sy_user.INSERT_DATE
   * @mbggenerated
   */
  public void setInsertDate(Date insertDate) {
    this.insertDate = insertDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sy_user.UPDATE_DATE
   *
   * @return the value of sy_user.UPDATE_DATE
   * @mbggenerated
   */
  public Date getUpdateDate() {
    return updateDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sy_user.UPDATE_DATE
   *
   * @param updateDate the value for sy_user.UPDATE_DATE
   * @mbggenerated
   */
  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  public String getVerifyCode() {
    return verifyCode;
  }

  public void setVerifyCode(String verifyCode) {
    this.verifyCode = verifyCode;
  }

  public String getBranchName() {
    return branchName;
  }

  public void setBranchName(String branchName) {
    this.branchName = branchName;
  }

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public Integer getAttribution() {
    return attribution;
  }

  public void setAttribution(Integer attribution) {
    this.attribution = attribution;
  }

  public Integer getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(Integer merchantId) {
    this.merchantId = merchantId;
  }

  public Integer getStoreId() {
    return storeId;
  }

  public void setStoreId(Integer storeId) {
    this.storeId = storeId;
  }

  public Integer getLastUpdateUser() {
    return lastUpdateUser;
  }

  public void setLastUpdateUser(Integer lastUpdateUser) {
    this.lastUpdateUser = lastUpdateUser;
  }

  public String getOriginPassword() {
    return originPassword;
  }

  public void setOriginPassword(String originPassword) {
    this.originPassword = originPassword;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public Date getCurrentLoginTime() {
    return currentLoginTime;
  }

  public void setCurrentLoginTime(Date currentLoginTime) {
    this.currentLoginTime = currentLoginTime;
  }

  public Integer getReceiveMsg() {
    return receiveMsg;
  }

  public void setReceiveMsg(Integer receiveMsg) {
    this.receiveMsg = receiveMsg;
  }

  public Integer getCancelAuth() {
    return cancelAuth;
  }

  public void setCancelAuth(Integer cancelAuth) {
    this.cancelAuth = cancelAuth;
  }

  public Integer getCanShareWeiXin() {
    return canShareWeiXin;
  }

  public void setCanShareWeiXin(Integer canShareWeiXin) {
    this.canShareWeiXin = canShareWeiXin;
  }

  public String getMerchantCod() {
    return merchantCod;
  }

  public void setMerchantCod(String merchantCod) {
    this.merchantCod = merchantCod;
  }

  public String getPrivateKey() {
    return privateKey;
  }

  public void setPrivateKey(String privateKey) {
    this.privateKey = privateKey;
  }

  public String getPublicKey() {
    return publicKey;
  }

  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyUser syUser = (SyUser) o;
    return Objects.equals(id, syUser.id)
        && Objects.equals(branchCod, syUser.branchCod)
        && Objects.equals(userCod, syUser.userCod)
        && Objects.equals(password, syUser.password)
        && Objects.equals(verifyCode, syUser.verifyCode)
        && Objects.equals(userName, syUser.userName)
        && Objects.equals(type, syUser.type)
        && Objects.equals(phone, syUser.phone)
        && Objects.equals(status, syUser.status)
        && Objects.equals(imgHead, syUser.imgHead)
        && Objects.equals(insertDate, syUser.insertDate)
        && Objects.equals(updateDate, syUser.updateDate)
        && Objects.equals(remark, syUser.remark)
        && Objects.equals(attribution, syUser.attribution)
        && Objects.equals(merchantId, syUser.merchantId)
        && Objects.equals(storeId, syUser.storeId)
        && Objects.equals(lastUpdateUser, syUser.lastUpdateUser)
        && Objects.equals(originPassword, syUser.originPassword)
        && Objects.equals(branchName, syUser.branchName)
        && Objects.equals(code, syUser.code)
        && Objects.equals(role, syUser.role)
        && Objects.equals(roleName, syUser.roleName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        id,
        branchCod,
        userCod,
        password,
        verifyCode,
        userName,
        type,
        phone,
        status,
        imgHead,
        insertDate,
        updateDate,
        remark,
        attribution,
        merchantId,
        storeId,
        lastUpdateUser,
        originPassword,
        branchName,
        code,
        role,
        roleName);
  }

  @Override
  public String toString() {
    return "SyUser{"
        + "id="
        + id
        + ", branchCod='"
        + branchCod
        + '\''
        + ", userCod='"
        + userCod
        + '\''
        + ", password='"
        + password
        + '\''
        + ", verifyCode='"
        + verifyCode
        + '\''
        + ", userName='"
        + userName
        + '\''
        + ", type='"
        + type
        + '\''
        + ", phone='"
        + phone
        + '\''
        + ", status='"
        + status
        + '\''
        + ", imgHead="
        + imgHead
        + ", insertDate="
        + insertDate
        + ", updateDate="
        + updateDate
        + ", remark='"
        + remark
        + '\''
        + ", attribution="
        + attribution
        + ", merchantId="
        + merchantId
        + ", storeId="
        + storeId
        + ", lastUpdateUser="
        + lastUpdateUser
        + ", originPassword='"
        + originPassword
        + '\''
        + ", branchName='"
        + branchName
        + '\''
        + ", code='"
        + code
        + '\''
        + ", role='"
        + role
        + '\''
        + ", roleName='"
        + roleName
        + '\''
        + ", currentLoginTime="
        + currentLoginTime
        + ", receiveMsg="
        + receiveMsg
        + '}';
  }
}
