package xzkbauth.common.jpa.entity;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;
import java.util.Objects;

/**
 *  分行表
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sy_branch
 *
 * @mbggenerated do_not_delete_during_merge
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@Entity
public class SyBranch {


    //ID
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    //分行码
    private String branchCod;
    //分行名称
    private String branchName;
    //分行内部户账号
    private String branchAccount;
    /**
     * 业务状态 0-正常 1-禁用 2-暂不对账
     */
    private Integer status;
    //备注
    private String remark;
    //插入时间
    private Date insertDate;
    //更新时间
    private Date updateDate;
    //小程序商户号
    private String corpNo;

}